### ISSUE TITLE
提示获取密钥失败

### ISSUE THREAD

**Issue by dklinux** [SuxueCode/WechatBakTool#11]
问题如图

<img width="573" alt="微信图片_20231201161220" src="https://github.com/SuxueCode/WechatPCMsgBakTool/assets/31166167/8d1fa801-7d95-409b-b244-d9e0d838bc67">
<img width="405" alt="c233cf47fe42572df7ba78e11171e2e" src="https://github.com/SuxueCode/WechatPCMsgBakTool/assets/31166167/d40d03a4-fdc6-4a18-89a9-1778040c7e7d">

**Comment by SuxueCode** [comment]
检查下版本是不是0.6.0.1

**Comment by tsuimanlung** [comment]
我用的最新版0.9.1.1也有这样的提示

**Comment by SuxueCode** [comment]
> 我用的最新版0.9.1.1也有这样的提示

使用的是用户名推断还是版本？版本请检查一下version.json里面是否支持，使用用户名的话，麻烦确认用户名是否正确
可以的话，最好进群，方便排查问题

**Comment by 737425152** [comment]
几个版本都是密钥失败  换电脑也是  一个win7 64位  一个win11 64位

**Comment by SuxueCode** [comment]
用户名的实现目前来看，并不是特别稳定，新增公钥头推断，可以试试那个，实在不行，地址保底
请确保是最新版本以及64位系统
