### ISSUE TITLE
建议：希望以后软件能够解密并且导出手机被分到电脑的聊天记录

### ISSUE THREAD

**Issue by 0Tune** [SuxueCode/WechatBakTool#12]
因为手机上面的聊天记录更加全面，所以希望以后电脑能够解密手机备份到电脑上的聊天记录，这样的话就真的无敌了

**Comment by SuxueCode** [comment]
手机上的聊天记录可以使用迁移功能，将手机记录合并到电脑上即可

**Comment by 0Tune** [comment]
> 手机上的聊天记录可以使用迁移功能，将手机记录合并到电脑上即可

迁移功能是把电脑上的聊天记录放到手机里吧，然后手机上能看合并后的记录
![QQ截图20231210121057](https://github.com/SuxueCode/WechatBakTool/assets/117656686/3fec4c7b-5acc-4fe4-8974-20e40ae6e9fa)

**Comment by SuxueCode** [comment]
在电脑上用迁移是电脑迁移到手机
在手机上用迁移是手机迁移到电脑

**Comment by 0Tune** [comment]
> 在电脑上用迁移是电脑迁移到手机 在手机上用迁移是手机迁移到电脑
看来是我自己不懂，谢谢了
![IMG_4638](https://github.com/SuxueCode/WechatBakTool/assets/117656686/1d7f5a36-35e2-4457-856d-4e46df20efec)

**Comment by SuxueCode** [comment]
回头我可以在readme更新下提醒

**Comment by 0Tune** [comment]
> 到底我可以在自述更新下提醒

辛苦
