### ISSUE TITLE
图片转换出现错误或文件不存在

### ISSUE THREAD

**Issue by lopeasd** [SuxueCode/WechatBakTool#13]
版本：0.9.1.1
导出群聊中的消息或者 单联系人消息时，导出不了图片。在导出的聊天记录中，原本图片的消息显示为：图片转换出现错误或文件不存在

**Comment by SuxueCode** [comment]
这个情况需要确认一下最原始的图片是否还存在，目前是原始图片不存在，不会获取缓存

**Comment by lopeasd** [comment]
原始图片是存在的，微信自动加密的。图片路径是在...\FileStorage\MsgAttach\[32位字符文件夹]\Image\[年份-月份]”文件夹中
图示如下：
![image](https://github.com/SuxueCode/WechatBakTool/assets/32991724/ce0f8a65-ccc7-48fe-894b-792a2b9764c3)

**Comment by SuxueCode** [comment]
麻烦加一下群，我看看是啥情况

**Comment by SuxueCode** [comment]
v0.9.3.0版本已经修复

**Comment by doraeomon** [comment]
图片转换出现错误或文件不存在  我尝试下电脑发送的图片能显示 用手机发送的就会出现图片转换出现错误或文件不存在

**Comment by SuxueCode** [comment]
因为手机上发的，不一定在本地有文件，可能是存在数据库内的缓存，现阶段缓存的图像暂时未取出，后续考虑支持
