### ISSUE TITLE
未找到适用于完成此操作的图像处理组件。

### ISSUE THREAD

**Issue by grayxh** [SuxueCode/WechatBakTool#14]
到处过程中报错，rt。
![Snipaste_2023-12-12_06-36-43](https://github.com/SuxueCode/WechatBakTool/assets/13599243/5f818142-3023-48ec-a1a5-fc14b791e46b)

**Comment by SuxueCode** [comment]
解密过程中的报错吗？
你关掉再开，工作区提示已解密还是未解密

**Comment by SuxueCode** [comment]
v0.9.3.0版本修复
