### ISSUE TITLE
关于自定义用户名

### ISSUE THREAD

**Issue by hametan** [SuxueCode/WechatBakTool#15]
关于自定义用户名的路径并非wxid时，使用用户名推断查找无法解密。3.9.8.15

**Comment by hametan** [comment]
> 非wxid也一样支持的，失败的话，方便进群一下吗，我可能要看一下现场

已经加了，还没通过 。

**Comment by SuxueCode** [comment]
原生自定义id，无法使用自定义推断，待打log看现场

**Comment by SuxueCode** [comment]
用户名的实现目前来看，并不是特别稳定，新增公钥头推断，可以试试那个，实在不行，地址保底
