### ISSUE TITLE
找不到资产文件

### ISSUE THREAD

**Issue by Yevanchen** [SuxueCode/WechatBakTool#17]
严重性	代码	说明	项目	文件	行	禁止显示状态	详细信息
错误	NETSDK1004	找不到资产文件“D:\新建文件夹 (2)\WechatBakTool-master\obj\project.assets.json”。运行 NuGet 包还原以生成此文件。	WechatBakTool	C:\Program Files\dotnet\sdk\8.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets	266		
![image](https://github.com/SuxueCode/WechatBakTool/assets/152952909/2bce2e69-477c-4df5-9e85-ee4e2e051ba3)

**Comment by SuxueCode** [comment]
说得很清楚了，还原nuget包

**Comment by Yevanchen** [comment]
xiexie 我的朋友
