### ISSUE TITLE
词云统计时type问题

### ISSUE THREAD

**Issue by STDquantum** [SuxueCode/WechatBakTool#19]
![image](https://github.com/SuxueCode/WechatBakTool/assets/60764289/6c2f1a67-2e03-401f-a46f-6bb5e28ef52d)
虽然说不建议留着一个字的关键词，但是如果用的话实现上似乎没有过滤掉一些非文本的strcontent，还是会出现像单个括号这种，甚至出现了一个revokemsg。还有些词比较明显是给ta的昵称里的，平常聊天中并没有涉及。应该都是xml的锅（）
希望可以修复这个问题

**Comment by SuxueCode** [comment]
单词太分散了，视觉效果并不好，因此我默认不把单词加入词云结果中
你也可以把单词屏蔽取消，然后去自定义词里面把一些标点符号去除掉即可
后续会抽成配置文件进行自定义配置，昨天加这个加得比较匆忙，先管实现而已
