### ISSUE TITLE
mac能不能更新下。

### ISSUE THREAD

**Issue by chenjunqiang** [SuxueCode/WechatBakTool#20]
从12年的聊天记录的电脑的硬盘还在。然后22年9月份的时候，电脑坏了，直接数据搞不回来了。

然后mac的硬盘是正常的，有拆开硬盘去看，是没问题的。

现在的数据只有从22年9月份开始，丢失了很多年的数据，好多还是家人的聊天记录，还有一些工作记录，

愿意付费。

**Comment by SuxueCode** [comment]
mac目前是不打算支持的，没有资源，也没有那么多精力去维护
你这个问题，我建议你看看能不能看看把数据迁移至虚拟机以后进行操作，然后MAC->手机->WIN PC
