### ISSUE TITLE
能否支持离线解密

### ISSUE THREAD

**Issue by uknowsec** [SuxueCode/WechatBakTool#25]
有些场景会获取到密钥和.db文件，大佬在后续版本中是否可以支持离线解密并展示聊天记录

**Comment by SuxueCode** [comment]
hw用的话，后续手动模式会规划，但是是怎么个形式，我还在考虑中
毕竟这个功能比较敏感一些，得好好考虑下风险规避的问题

**Comment by Shurrik0030** [comment]
+1

**Comment by ColdMoon-zcm** [comment]
为什么要登陆才能获取呢，登陆是为了获取微信名和db吗，微信名可以从文件夹知道，那么是不是直接使用本地文件就能解密了呢，现在表情预下载功能是什么意思，是指聊天中发出的表情吗，现在是下载不了的。
