### ISSUE TITLE
数据库磁盘印象错误

### ISSUE THREAD

**Issue by gewenlong365** [SuxueCode/WechatBakTool#26]
database disk image is malformed
![image](https://github.com/SuxueCode/WechatBakTool/assets/78864083/65893aa1-538a-46fb-9c14-47bccd1ea1b2)

**Comment by SuxueCode** [comment]
请检查软件所在分区是否还有空间

**Comment by gewenlong365** [comment]
> 请检查软件所在分区是否还有空间

不好意思，我重新登陆了微信并且删除了软件重新解压之后成功了，这不是一个问题
