### ISSUE TITLE
获取不到微信进程和路径

### ISSUE THREAD

**Issue by clearlove88888** [SuxueCode/WechatBakTool#29]
在一台win7的电脑上成功导出了，是通过安装在移动硬盘上的软件导出的。
在另一台win11的电脑上新建工作区后，获取不到微信的进程
是因为操作系统版本的原因还是我没有安装微信到默认目录呢？
版本22H2 OS内部版本22621.2861 win11企业版

**Comment by SuxueCode** [comment]
右键，管理员打开试试
