### ISSUE TITLE
从.net6改成.net4.8运行效率低

### ISSUE THREAD

**Issue by ColdMoon-zcm** [SuxueCode/WechatBakTool#30]
我发现解密得到数据不是很及时，我想着做成windows服务挂载，但是用.net4.8运行的效率极其低，是不是因为.net 的框架版本问题导致的。

**Comment by SuxueCode** [comment]
解密得到数据不是很及时是什么意思？

**Comment by ColdMoon-zcm** [comment]
手机上收发消息电脑上也会看到，但是解密后看到的还是历史数据。还有就是在原本代码上解密一千万条数据几秒完成，我用控制台写的几个小时都跑不完是什么原因呢


来自 MEIZU 20 Pro

-------- 原始邮件 --------
发件人：Suxue ***@***.***>
时间：2023年12月29日 11:01
收件人：SuxueCode/WechatBakTool ***@***.***>
抄送：ColdMoon ***@***.***>,Author ***@***.***>
主题：Re: [SuxueCode/WechatBakTool] 从.net6改成.net4.8运行效率低 (Issue #30)

**Comment by SuxueCode** [comment]
微信不是实时写入数据进数据库，必须关闭后才会把缓存写入库，你想试试读取聊天记录不太可能
解密不清楚情况，不好说是什么问题

**Comment by ColdMoon-zcm** [comment]
ok我再研究下效率问题


来自 MEIZU 20 Pro

-------- 原始邮件 --------
发件人：Suxue ***@***.***>
时间：2023年12月29日 11:39
收件人：SuxueCode/WechatBakTool ***@***.***>
抄送：ColdMoon ***@***.***>,Author ***@***.***>
主题：Re: [SuxueCode/WechatBakTool] 从.net6改成.net4.8运行效率低 (Issue #30)

**Comment by SuxueCode** [comment]
觉得项目不错可以点个star
