### ISSUE TITLE
已解密但是没有聊天记录

### ISSUE THREAD

**Issue by wamian1939** [SuxueCode/WechatBakTool#31]
<img width="113" alt="错误" src="https://github.com/SuxueCode/WechatBakTool/assets/151725938/632d0a8d-bc47-4b77-9e53-fb4ef44b8886">

**Comment by SuxueCode** [comment]
检查MSGX.DB是否成功解密

**Comment by SuxueCode** [comment]
是昨晚下载的吗，昨晚下载的回滚上一个版本，那个版本有潜在问题
