### ISSUE TITLE
建议全部导出增加一个暂停功能

### ISSUE THREAD

**Issue by liuhaha573749877** [SuxueCode/WechatBakTool#32]
![aaaaa](https://github.com/SuxueCode/WechatBakTool/assets/67892232/43c33023-4f2b-4dd0-96d4-59dd6361a78e)

**Comment by SuxueCode** [comment]
这个我看看，不过更可能会出的是中断，因为这个方便

**Comment by liuhaha573749877** [comment]
> 这个我看看，不过更可能会出的是中断，因为这个方便
哈哈哈，感谢作者热心回复，还有一个选择好友，全部导出之后，会导出无用的公众号的记录，然后导出的文件没有备注，全是微信号，是我哪一步搞错了吗？
![bbbbbbbb](https://github.com/SuxueCode/WechatBakTool/assets/67892232/5981affb-9729-474b-859f-f2caab892576)

**Comment by SuxueCode** [comment]
回头会过滤一下

**Comment by liuhaha573749877** [comment]
感谢感谢

**Comment by SuxueCode** [comment]
新版本已经完成添加
