### ISSUE TITLE
有考虑增加解密微信pc端的手机备份文件功能吗？

### ISSUE THREAD

**Issue by fanxing-6** [SuxueCode/WechatBakTool#34]
微信至今也不支持同步完整聊天记录到PC端
![image](https://github.com/SuxueCode/WechatBakTool/assets/73698197/5854fa03-0d5e-4882-ad60-2071b56cb384)

**Comment by SuxueCode** [comment]
解不了，迁移不能完整迁移？

**Comment by fanxing-6** [comment]
![image](https://github.com/SuxueCode/WechatBakTool/assets/73698197/bbb071b0-fcba-428e-a472-161dc4f890f9)
迁移是吧聊天记录迁移到手机上，备份是将手机记录备份到电脑上（但是电脑看不了）有需要恢复到手机，如果电脑微信的聊天记录不完整，貌似没有办法恢复完整的（PC端）聊天记录

**Comment by SuxueCode** [comment]
麻烦看一下项目说明的**部分问题章节的加粗部分**
