### ISSUE TITLE
我直接拿来改版

### ISSUE THREAD

**Issue by Kedren** [SuxueCode/WechatBakTool#35]
<img width="1440" alt="image" src="https://github.com/SuxueCode/WechatBakTool/assets/33985542/3aee7e42-393d-4309-b38d-0e0f6eb228a9">
<img width="1440" alt="image" src="https://github.com/SuxueCode/WechatBakTool/assets/33985542/c267323f-fce6-4123-91bc-75549ac19145">

**Comment by Kedren** [comment]
blazor做UI很香

**Comment by SuxueCode** [comment]
非常棒，但是我在规划时本来就不太考虑使用web来提供服务，定位就是在桌面客户端。
如果使用web的话，我可能更考虑是用vue+后端接口的方式，而不是使用blazor，但是这样太重了，不是我的初衷。

**Comment by fangyuan99** [comment]
可以分享一下您这个改版吗？我想导出带UI的
