### ISSUE TITLE
新建工作区卡在no such table: ContactHeadlmg1

### ISSUE THREAD

**Issue by NineFourths** [SuxueCode/WechatBakTool#36]
![微信截图_20240122112103](https://github.com/SuxueCode/WechatBakTool/assets/85357278/a2419500-73a1-464c-af0f-2e3a241a9d30)
请问一下新建工作区时候会弹窗no such table: ContactHeadlmg1，而解密方式除了图中所选的，其他两个都是找不到密钥的

**Comment by SuxueCode** [comment]
微信版本多少？

**Comment by NineFourths** [comment]
> 微信版本多少？

3.9.9.27
![image](https://github.com/SuxueCode/WechatBakTool/assets/85357278/f829b11c-49c1-49a4-a154-2d817b74a13b)

**Comment by SuxueCode** [comment]
目前我微信还没更新到这个版本，你在version.json里面加3.9.9.27版本，然后用固定地址查找试试
`{
		"Version":"3.9.9.27",
		"BaseAddr": 68066576
	}`
