### ISSUE TITLE
err.log按提示提交ISSUE

### ISSUE THREAD

**Issue by rogerfederal** [SuxueCode/WechatBakTool#37]
{"LocalId":80223,"MsgSequence":671824805,"Type":3,"SubType":0,"CreateTime":1554597543,"IsSender":false,"MsgSvrID":"8161939939925005935","StrTalker":"5227036437@chatroom","StrContent":"<?xml version=\"1.0\"?>\n<msg>\n\t<img aeskey=\"e057c6c563ed7ef01312a09df4e7dc86\" encryver=\"0\" cdnthumbaeskey=\"e057c6c563ed7ef01312a09df4e7dc86\" cdnthumburl=\"3053020100044c304a0201000204a910866d02032f53a302040b762d7002045ca946740425617570696d675f366333383038313933306130396337615f313535343539373438333333370204010818020201000400\" cdnthumblength=\"5500\" cdnthumbheight=\"120\" cdnthumbwidth=\"88\" cdnmidheight=\"0\" cdnmidwidth=\"0\" cdnhdheight=\"0\" cdnhdwidth=\"0\" cdnmidimgurl=\"3053020100044c304a0201000204a910866d02032f53a302040b762d7002045ca946740425617570696d675f366333383038313933306130396337615f313535343539373438333333370204010818020201000400\" length=\"102439\" md5=\"81e099ecf15915f076c426ac9b773f12\" />\n</msg>\n","DisplayContent":"[界面未支持格式]Type=3","CompressContent":null,"BytesExtra":"CgQIBRABCgQIBhAAGhcIARITd3hpZF82d3ljbHdpMHo3YmcyMhq+AQgHErkBPG1zZ3NvdXJjZT48c2VxdWVuY2VfaWQ+NjcxODI0ODA1PC9zZXF1ZW5jZV9pZD4KCTxzaWxlbmNlPjA8L3NpbGVuY2U+Cgk8bWVtYmVyY291bnQ+MTA0PC9tZW1iZXJjb3VudD4KCTxOb3RBdXRvRG93bmxvYWRSYW5nZT4yMDowMC0yMjowMDswMDowMC0wMTowMDwvTm90QXV0b0Rvd25sb2FkUmFuZ2U+CjwvbXNnc291cmNlPgoaJAgCEiA0YzM2MjlmZTc1ZGRkZWFmMTRhN2EyMTQ4NDI1YWUxMxpPCAQSS2hlbmdkZW1hb3hpblxGaWxlU3RvcmFnZVxJbWFnZVwyMDE5LTA0XDM0ODJiYzRhZjY5YzY2ZjVhY2JkNjkxYzVmMWM0MjdhLmRhdBpXCAMSU2hlbmdkZW1hb3hpblxGaWxlU3RvcmFnZVxJbWFnZVxUaHVtYlwyMDE5LTA0XDY4MmRhZGI3ZjdiNDMxMzUzNjMxMzRhOTE1MjM5ZDUwX3QuZGF0","NickName":"xxxxxxxxxxxxxxxx"}System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at WechatBakTool.Helpers.DecryptionHelper.CheckFileType(Byte[] data) in D:\Code\WechatPCMsgBakTool\Helpers\DecryptionHelper.cs:line 347
   at WechatBakTool.WXUserReader.DecryptAttachment(WXMsgType type, String path, String username) in D:\Code\WechatPCMsgBakTool\WXUserReader.cs:line 662
   at WechatBakTool.WXUserReader.GetAttachment(WXMsgType type, WXMsg msg) in D:\Code\WechatPCMsgBakTool\WXUserReader.cs:line 605
   at WechatBakTool.Export.HtmlExport.SetMsg(WXUserReader reader, WXContact contact, WorkspaceViewModel viewModel) in D:\Code\WechatPCMsgBakTool\Export\HtmlExport.cs:line 83

**Comment by SuxueCode** [comment]
这图片保存下来是什么类型?

**Comment by rogerfederal** [comment]
> IndexOutOfRangeException

请问哪里可以看到图片的路径呢？

**Comment by SuxueCode** [comment]
这里不显示路径的，得看数据库匹配
