### ISSUE TITLE
微信安装路径非默认路径，读不到聊天记录内容？

### ISSUE THREAD

**Issue by xiao-xiaozi** [SuxueCode/WechatBakTool#38]
这是获取到的微信路径，但我更改过安装位置，在另一个盘。
![image](https://github.com/SuxueCode/WechatBakTool/assets/50149380/80ea0f20-db06-47d5-b6a8-2ab1e429bd45)

工作区建立后，没有数据。
![image](https://github.com/SuxueCode/WechatBakTool/assets/50149380/92a7319e-204f-4d15-9b18-cbba56b90330)

微信版本：3.9.927

WechatBakTool版本：0.9.6.1

**Comment by xiao-xiaozi** [comment]
![image](https://github.com/SuxueCode/WechatBakTool/assets/50149380/f46a7805-87a6-4736-8c71-2e8ffa45e560)
WechatBakTool版本：0.9.6.1

**Comment by xiao-xiaozi** [comment]
【误操作关闭了，见谅。】


WechatBakTool版本：0.9.7.2 版本，出现以下提示弹窗
![image](https://github.com/SuxueCode/WechatBakTool/assets/50149380/4ccd5b9c-6da2-4f8b-a623-16ed2a9cc319)

**Comment by SuxueCode** [comment]
解密失败了，用查找地址去解密，最近秘钥头失效了

**Comment by xiao-xiaozi** [comment]
> 解密失败了，用查找地址去解密，最近秘钥头失效了

感谢，用查找地址解密方式后可以了。
