### ISSUE TITLE
【建议】采用blazor搭建离线分析系统

### ISSUE THREAD

**Issue by bigsinger** [SuxueCode/WechatBakTool#43]
模式可以参考：https://github.com/xaoyaoo/PyWxDump

建议把取证端和分析端分开，取证端只做必要信息的获取。
分析端参考 https://github.com/xaoyaoo/PyWxDump ，使用C#的简单易用的blazor框架搭建离线分析系统。

其他建议：代码有点混乱，可以使用chat gpt助手辅助，效率也高一些。

**Comment by SuxueCode** [comment]
最近时间可能不是很多，因为在大设计上有过变动，部分东西还没来得及解耦，自然代码也就没时间整理。
目前是不打算拆分，设计上来说，把取证和分析分开，个人觉得完全没必要，因为需求就这么多，没必要把面摊大。
对于普通人群而言，提供一个一体化的工具，可能更合适他们，他们的用途非常简单，我就是要备份聊天记录，没了。所以尽可能简化步骤是这部分的目标。
对于专业人群而言，提供差异化的配置项，可能更合适，后面规划有手动模式，可以自己把解密后的db导进工作区，即可分析。

以上是我个人的看法，感谢反馈 :)

**Comment by bigsinger** [comment]
> 最近时间可能不是很多，因为在大设计上有过变动，部分东西还没来得及解耦，自然代码也就没时间整理。 目前是不打算拆分，设计上来说，把取证和分析分开，个人觉得完全没必要，因为需求就这么多，没必要把面摊大。 对于普通人群而言，提供一个一体化的工具，可能更合适他们，他们的用途非常简单，我就是要备份聊天记录，没了。所以尽可能简化步骤是这部分的目标。 对于专业人群而言，提供差异化的配置项，可能更合适，后面规划有手动模式，可以自己把解密后的db导进工作区，即可分析。
> 
> 以上是我个人的看法，感谢反馈 :)

是否考虑做舆情分析，就是利用聊录的数据（例如某群），可以：
1、统计分析每天的聊天条数折线图；
2、主要关键词分析出热点，例如：热点话题、主要事件、国家区域、投资热门板块等；

**Comment by Dribbling** [comment]
> > 最近时间可能不是很多，因为在大设计上有过变动，部分东西还没来得及解耦，自然代码也就没时间整理。 目前是不打算拆分，设计上来说，把取证和分析分开，个人觉得完全没必要，因为需求就这么多，没必要把面摊大。 对于普通人群而言，提供一个一体化的工具，可能更合适他们，他们的用途非常简单，我就是要备份聊天记录，没了。所以尽可能简化步骤是这部分的目标。 对于专业人群而言，提供差异化的配置项，可能更合适，后面规划有手动模式，可以自己把解密后的db导进工作区，即可分析。
> > 以上是我个人的看法，感谢反馈 :)
> 
> 是否考虑做舆情分析，就是利用聊录的数据（例如某群），可以： 1、统计分析每天的聊天条数折线图； 2、主要关键词分析出热点，例如：热点话题、主要事件、国家区域、投资热门板块等；

这个导出html之后用别的工具就可以做了,应该没必要重复造轮子
