### ISSUE TITLE
no such table:ContactHeadImg1

### ISSUE THREAD

**Issue by yuht** [SuxueCode/WechatBakTool#45]
软件版本 0.9.7.2
windows微信版本：3.9.9.43

安装完毕微信，同步信息。分析的时候出现错误，显示no such table:ContactHeadImg1

**Comment by SuxueCode** [comment]
删除工作区，用固定地址重新获取解密

**Comment by yuht** [comment]
> 删除工作区，用固定地址重新获取解密
新建工作区， 使用固定地址查找【保底】，也是出现这个错误。在这个错误出现之前，提示的是解密xinfo.db。 错误复现和公钥头推断查找【推荐】是一样的错误。

**Comment by GitHub-PeterX** [comment]
使用了.net framework6.0，但是按您的教程发现无法解密，提示：no such table:ContactHeadImg1
可以帮忙下么，谢谢

**Comment by stpanzj** [comment]
> 软件版本 0.9.7.2 windows微信版本：3.9.9.43
> 
> 安装完毕微信，同步信息。分析的时候出现错误，显示no such table:ContactHeadImg1

我也是一样，包括后面的错误。我更新了微信版本，从3.9.7到3.9.9，就可以建立工作区。

**Comment by SuxueCode** [comment]
我总结一下，这个问题大概率现在是没办法获取到秘钥，建议确保微信是version.json内支持的版本，并且使用固定地址查找
