### ISSUE TITLE
win10版本打开v0.9.7.3版本没有反应，有稳定版吗

### ISSUE THREAD

**Issue by wangding01** [SuxueCode/WechatBakTool#52]

**Comment by SuxueCode** [comment]
运行时安装了吗，确定文件完整吗

**Comment by wangding01** [comment]
必须是6.0的版本吗

**Comment by wangding01** [comment]
运行时必须是6.0的版本吗？我是6.0.1的貌似不行

**Comment by SuxueCode** [comment]
注意是.net 6.0的桌面运行时

**Comment by wangding01** [comment]
.NET 6.0 Desktop Runtime (v6.0.0) ？

**Comment by SuxueCode** [comment]
是的

**Comment by wangding01** [comment]
仍然不行，打开没有反应😫

**Comment by wangding01** [comment]
![image](https://github.com/SuxueCode/WechatBakTool/assets/44080023/1b40cc22-46fc-44dd-9aef-b8c362d1f25a)

**Comment by SuxueCode** [comment]
事件查看器看看有没有.net runtime error，把上下文贴给我

**Comment by wangding01** [comment]
我加你QQ群了，你通过一下，我们群里说吧
