### ISSUE TITLE
0.9.7.3报了错误：no such table: ContactHeadlmg1

### ISSUE THREAD

**Issue by zzlKevin** [SuxueCode/WechatBakTool#53]
0.9.7.3报了错误：no such table: ContactHeadlmg1

**Comment by SuxueCode** [comment]
什么版本，什么方式

**Comment by muxi87** [comment]
微信版本3.9.10.19， 固定地址查找-获取到的秘钥为空，解密失败；用户名推荐查找-获取到的秘钥为空，解密失败；公钥头推荐查找-no such table: ContactHeadlmg1，使用0.9.7.2版本也是一样报错，是什么原因呢，急等回复，谢谢。

**Comment by SuxueCode** [comment]
> 微信版本3.9.10.19， 固定地址查找-获取到的秘钥为空，解密失败；用户名推荐查找-获取到的秘钥为空，解密失败；公钥头推荐查找-no such table: ContactHeadlmg1，使用0.9.7.2版本也是一样报错，是什么原因呢，急等回复，谢谢。

3.9.10.19不在version.json内支持，要么降级微信，要么自己找3.9.10.19的key地址，加到version.json内用地址查找。

**Comment by muxi87** [comment]
目前0.9.7.3版本支持到哪个微信版本呢

**Comment by SuxueCode** [comment]
> 目前0.9.7.3版本支持到哪个微信版本呢

刚刚找了一下，更新新版本把，用固定地址查找

**Comment by muxi87** [comment]
新版0.9.7.5-用固定地址查找已解决以上问题，必须点个大大的赞！！！

**Comment by shengshifanhua** [comment]
首先查看version.json内是否有自己的微信版本，其次卸载微信客户端装一个符合的版本，或重装。
