### ISSUE TITLE
提示获取到的密钥为空，怎么办啊？

### ISSUE THREAD

**Issue by liuzhaoyzz** [SuxueCode/WechatBakTool#56]
无论用公钥头推断查找，还是用固定地址查找，都提示获取到的密钥为空，怎么办啊？
![QQ截图20240526083151](https://github.com/SuxueCode/WechatBakTool/assets/9776716/2851079f-696b-46a4-b60c-3ca1ef750fe6)

**Comment by maki-nagisa** [comment]
一眼就看出 你微信号都没输入正确 当然密钥错误

**Comment by liuzhaoyzz** [comment]
默认打开的“微信名”，和我自己的“微信号”，我都试了都不行。我截图你看下。
![QQ截图20240528174646](https://github.com/SuxueCode/WechatBakTool/assets/9776716/29e36e4b-841f-48d0-9ec8-636297679cfa)
![QQ截图20240528174630](https://github.com/SuxueCode/WechatBakTool/assets/9776716/745e6014-bb2b-4996-abc6-75865ad4f58e)

**Comment by SuxueCode** [comment]
固定地址不依赖微信号，请检查微信版本是否在version.json内有支持，近期请使用固定地址进行解密

**Comment by liuzhaoyzz** [comment]
1、我的微信的版本是3.8.0.41，为什么用旧版本？因为旧版本的word发来之后，文件不是只读的。
version.json没有包含该版本，都是3.9.x版本的。

2、固定地址我试了也不行，一楼已经说过了。

**Comment by SuxueCode** [comment]
不包含那自然解密不了，只能更新微信版本
因为早期的微信不一定是64位的

**Comment by gubabagu** [comment]
新版本微信在设置里可以修改文件的【只读】选项。
![image](https://github.com/user-attachments/assets/0324fb00-8329-415d-9e0c-90476ae753af)
