### ISSUE TITLE
无法导出微信3.9.10.27版记录

### ISSUE THREAD

**Issue by muxi87** [SuxueCode/WechatBakTool#60]
什么时候可以升级WechatBakTool 0.9.7.5版本程序以便支持微信3.9.10.27版的记录导出呢？微信版本更新得有些快了。

**Comment by SuxueCode** [comment]
可以自己添加version.json
{
    "Version":"3.9.10.27",
    "BaseAddr": 95126928
}

**Comment by SuxueCode** [comment]
version.json内按json格式添加上去就好了，然后用固定地址查找

**Comment by muxi87** [comment]
![cf913cc5547c45976891e8bd3792b40](https://github.com/SuxueCode/WechatBakTool/assets/167592383/e0eb5e76-16ad-4b8c-a0c2-ece52316cc65)
更改后用固定地址查找，报错如图所示，是格式不对吗？

**Comment by SuxueCode** [comment]
json没加对，检查格式

**Comment by muxi87** [comment]
已完善OK
