### ISSUE TITLE
BaseAddr的数字码问题

### ISSUE THREAD

**Issue by muxi87** [SuxueCode/WechatBakTool#63]
![base address](https://github.com/SuxueCode/WechatBakTool/assets/167592383/6eac6eb0-bbaf-4b95-8d1b-aefc18f7c99b)
BaseAddr后的这串8位数字逻辑是什么呢？比如3.9.11.17的版本，BaseAddr后应该再version.json文本中更新什么数字穿呢？
{
"Version":"3.9.11.17",
"BaseAddr": ？？？？？？？？
}

**Comment by SuxueCode** [comment]
key的内存地址

**Comment by muxi87** [comment]
好的，谢谢~

**Comment by muxi87** [comment]
![1719203356207](https://github.com/SuxueCode/WechatBakTool/assets/167592383/53685a64-ad65-4932-9566-170525b58168)
![1719203402568](https://github.com/SuxueCode/WechatBakTool/assets/167592383/2e5b7420-0070-416e-96c1-89fe0a203009)
用CE刷出3.9.11.17版本的add是5937c50,换算成10进制是93551696，刷回version.json-BaseAddr后显示密钥为空，获取失败。求问是key换算错了吗？

**Comment by SuxueCode** [comment]
这块得你自己研究了，因为基址这块的维护我别人反馈合并过来的

**Comment by muxi87** [comment]
好的，谢谢。
