### ISSUE TITLE
获取到的密钥为空，获取失败

### ISSUE THREAD

**Issue by 727729853** [SuxueCode/WechatBakTool#68]
![image](https://github.com/user-attachments/assets/88984ab0-4a96-4770-837b-5c2a725b3aa0)
微信版本：3.9.11.25  看了version.json是支持的
下方显示的微信号也是对的。

**Comment by SuxueCode** [comment]
请使用固定地址获取

**Comment by 727729853** [comment]
好的，感谢回复
