### ISSUE TITLE
请问导出的记录可以导回到微信吗？

### ISSUE THREAD

**Issue by mreasonlin** [SuxueCode/WechatBakTool#71]
请问导出的记录可以导回到微信吗？导出的html不小心删了就剩文件夹了，文件还在，有办法补救吗
![屏幕截图 2024-10-28 181240](https://github.com/user-attachments/assets/a3c2cb70-a465-4e02-911a-f89408b3662f)

**Comment by SuxueCode** [comment]
不能，我导出时候是复制消息数据库，不会影响微信本身的消息
