### ISSUE TITLE
本次导出发生了异常，部分消息被跳过...

### ISSUE THREAD

**Issue by hxi667** [SuxueCode/WechatBakTool#74]
您好，我在将聊天记录导出为HTML格式时，最后提示：
![image](https://github.com/user-attachments/assets/3f073d50-3286-481d-ab0f-a57cda9d12dd)
Err.log中内容如下：

{"LocalId":37130,"MsgSequence":812259299,"Type":3,"SubType":0,"CreateTime":1700237950,"IsSender":true,"MsgSvrID":"8224042687602659712","StrTalker":"wxid_glqprfx82h4u21","StrContent":"<?xml version=\"1.0\"?>\n<msg>\n\t<img aeskey=\"445b02963e0ba236849a8fd07df2fdb3\" encryver=\"1\" cdnthumbaeskey=\"445b02963e0ba236849a8fd07df2fdb3\" cdnthumburl=\"3057020100044b30490201000204fd4b69aa02032f559702047caf1e7002046557927e042437653339623339352d636430622d343232362d616231312d6164336364373137383063640204051818020201000405004c51e700\" cdnthumblength=\"3225\" cdnthumbheight=\"120\" cdnthumbwidth=\"67\" cdnmidheight=\"0\" cdnmidwidth=\"0\" cdnhdheight=\"0\" cdnhdwidth=\"0\" cdnmidimgurl=\"3057020100044b30490201000204fd4b69aa02032f559702047caf1e7002046557927e042437653339623339352d636430622d343232362d616231312d6164336364373137383063640204051818020201000405004c51e700\" length=\"61074\" md5=\"62054e1013a4ce53c4d2f4c4a7195fd8\" />\n\t<appinfo>\n\t\t<appid>wxc35d3c9d0a795170</appid>\n\t\t<version>17</version>\n\t\t<appname>虎扑App</appname>\n\t\t<isforceupdate>0</isforceupdate>\n\t\t<messageaction></messageaction>\n\t\t<messageext></messageext>\n\t\t<mediatagname></mediatagname>\n\t</appinfo>\n\t<platform_signature></platform_signature>\n\t<imgdatahash></imgdatahash>\n</msg>\n","DisplayContent":"[界面未支持格式]Type=3","CompressContent":null,"BytesExtra":"CgQIEBAACgQIBRABCgQIBhAAGrUDCAcSsAM8bXNnc291cmNlPgogICAgPGJpemZsYWc+MDwvYml6ZmxhZz4KICAgIDxhbG5vZGU+CiAgICAgICAgPGZyPjI8L2ZyPgogICAgPC9hbG5vZGU+CiAgICA8c2VjX21zZ19ub2RlPgogICAgICAgIDx1dWlkPmE5ODk4MTU3NTcyOWVlYmYyZjNlYzUzMTA2ZTE5MWU3XzwvdXVpZD4KICAgICAgICA8YWxub2RlPgogICAgICAgICAgICA8ZnI+MTwvZnI+CiAgICAgICAgPC9hbG5vZGU+CiAgICA8L3NlY19tc2dfbm9kZT4KICAgIDxpbWdtc2dfcGQgY2RubWlkaW1ndXJsX3NpemU9IjYxMDc0IiBjZG5taWRpbWd1cmxfcGRfcHJpPSI1MCIgY2RubWlkaW1ndXJsX3BkPSIxIiAvPgogICAgPHNpZ25hdHVyZT52MV9KZ1NIQ3BsSDwvc2lnbmF0dXJlPgogICAgPHRtcF9ub2RlPgogICAgICAgIDxwdWJsaXNoZXItaWQgLz4KICAgIDwvdG1wX25vZGU+CjwvbXNnc291cmNlPgoaJAgCEiA4MTExNmE0NGU4NTgyNzlkZDAwZjk1MDRjYzQwODk3YRqBAQgEEn13eGlkX2wxM2FscmZleTR5azIyXEZpbGVTdG9yYWdlXE1zZ0F0dGFjaFw0YWRiOTE2MTQ3NzY5NDI0ODM0YWFlODFmMGMzZDBhNFxJbWFnZVwyMDIzLTExXDUzODkwNTRjZDkwYWFiYjQxNDk1YjA4MGJiZWFiYmY4LmRhdBqDAQgDEn93eGlkX2wxM2FscmZleTR5azIyXEZpbGVTdG9yYWdlXE1zZ0F0dGFjaFw0YWRiOTE2MTQ3NzY5NDI0ODM0YWFlODFmMGMzZDBhNFxUaHVtYlwyMDIzLTExXGFlOGIwMjNiNzYyYjhjMTFhMTE5M2YwYjIzMjgzNzQ1X3QuZGF0","NickName":"我"}System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at WechatBakTool.Helpers.DecryptionHelper.CheckFileType(Byte[] data) in D:\Code\WPF\WechatPCMsgBakTool\Helpers\DecryptionHelper.cs:line 347
   at WechatBakTool.WXUserReader.DecryptAttachment(WXMsgType type, String path, String username) in D:\Code\WPF\WechatPCMsgBakTool\WXUserReader.cs:line 713
   at WechatBakTool.WXUserReader.GetAttachment(WXMsgType type, WXMsg msg) in D:\Code\WPF\WechatPCMsgBakTool\WXUserReader.cs:line 684
   at WechatBakTool.Export.HtmlExport.SetMsg(WXUserReader reader, WXContact contact, WorkspaceViewModel viewModel, DatetimePickerViewModel dateModel) in D:\Code\WPF\WechatPCMsgBakTool\Export\HtmlExport.cs:line 83

**Comment by SuxueCode** [comment]
异常消息主要还是由于类型没适配或者附件不存在导致的比较多，这个暂时不考虑处理先了，大版本会重新梳理数据类型
